---
abstract: "Sorry I can't dance, I'm hanging on to my friend's purse"
author:
  - 'Philippe Bruhat (BooK) <book@cpan.org>'
build_requires:
  File::Find: 0
  File::Spec: 0
  File::Temp: 0
  List::Util: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300005, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Wallflower
requires:
  Carp: 0
  Exporter: 0
  Getopt::Long: 0
  HTML::LinkExtor: 0
  HTTP::Date: 0
  HTTP::Headers: 0
  Path::Class: 0
  Plack::Util: 0
  Pod::Find: 0
  Pod::Usage: 0
  URI: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=App-Wallflower
  repository: http://github.com/book/App-Wallflower.git
version: 1.003
