---
abstract: 'Class performing the moves for the wallflower program'
author:
  - 'Philippe Bruhat (BooK) <book@cpan.org>'
build_requires:
  List::Util: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Wallflower
provides:
  App::Wallflower:
    file: lib/App/Wallflower.pm
    version: 1.000
requires:
  Path::Class: 0
  Plack: 0
  URI: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/book/App-Wallflower
version: 1.000
